name: WeatheringBlocks
version: '1.0-SNAPSHOT'
main: me.stephenminer.weatheringBlocks.WeatheringBlocks
api-version: '1.16'
load: POSTWORLD
softdepend:
  - WorldGuard
commands:
  waxify:
  weatheringitem:
